# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spotify-Front' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spotify-Front
  pod 'MSPeekCollectionViewDelegateImplementation'
  pod 'SnapKit'
  pod 'UIImageColors'
  pod 'Moya'
  pod 'Kingfisher' 
  target 'Spotify-FrontTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Spotify-FrontUITests' do
    # Pods for testing
  end

end
